export const CURRENT_CUSTOMER_ID = 'CURRENT_CUSTOMER_ID';

export const GET_LIST_CUSTOMER = 'GET_LIST_CUSTOMER';

export const GET_LIST_PHONE = 'GET_LIST_PHONE';

export const REMOVE_PHONE = 'REMOVE_PHONE';

export const SET_LIST_PHONE = 'SET_LIST_PHONE';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';

export const CURRENT_CUSTOMER_ID_FINDER = 'CURRENT_CUSTOMER_ID_FINDER';